import { Ally, ContainerItem, Archetype } from './Types';

// Default Substance Allies (Keeping existing allies)
export const DEFAULT_ALLIES: Ally[] = [
  {
    id: 'firestarter',
    name: 'Stimulants',
    mythicName: 'Firestarter',
    face: '🔥',
    invocation: 'May this flame light what matters, not what merely demands.',
    function: 'Ignites focus, momentum, motion — reminds the nervous system of possibility.',
    shadow: 'Mistakes speed for progress; burns through rest, not toward it.',
    ritual: 'Before dosing — place one hand on your chest, feel the heartbeat you\'re about to quicken. Whisper: "Burn bright, not away."',
    log: [],
  },
  {
    id: 'mirror',
    name: 'Entheogens',
    mythicName: 'Mirror & Mystery',
    face: '🔮',
    invocation: 'Show me myself as cosmos, but bring me back whole.',
    function: 'Expands the membrane between self and all — reveals the divine recursion in experience.',
    shadow: 'Reveals too much too fast — replaces integration with revelation.',
    ritual: 'Before the threshold, speak one truth you\'re willing to lose and one you wish to keep.',
    log: [],
  },
  {
    id: 'chalice',
    name: 'Alcohol',
    mythicName: 'The Hollow Chalice',
    face: '🍷',
    invocation: 'Let this cup open warmth, not emptiness.',
    function: 'Loosens the social heart, dissolves distance, invites song.',
    shadow: 'Hollows the self in the name of connection.',
    ritual: 'Touch your glass to your lips, then pause — breathe once before the sip. Ask: "Am I joining, or escaping?"',
    log: [],
  },
  {
    id: 'tinkerer',
    name: 'Nicotine',
    mythicName: 'The Tinkerer',
    face: '💨',
    invocation: 'Let curiosity spark, not spiral.',
    function: 'Sharpens attention, traces detail, ritualizes pause.',
    shadow: 'Turns precision into obsession; mistake control for safety.',
    ritual: 'Exhale deliberately. Watch the smoke/diffusion fade and whisper: "Release what I tried to fix."',
    log: [],
  },
  {
    id: 'entropy',
    name: 'Opioids',
    mythicName: "Entropy's Embrace",
    face: '⚫',
    invocation: 'Hold me until I can hold myself.',
    function: 'Teaches surrender, relief, and the grace of rest.',
    shadow: 'Makes oblivion seductive; trades awareness for absence.',
    ritual: 'Before contact — press a hand into the earth, bed, or floor. Feel gravity\'s embrace and say: "May I return."',
    log: [],
  },
  {
    id: 'godmother',
    name: 'Cannabis',
    mythicName: 'Green Godmother',
    face: '🍃',
    invocation: 'Let me see the pattern without losing form.',
    function: 'Bridges sensory and symbolic worlds — a translator between logic and intuition.',
    shadow: 'Turns awe into apathy; mists clarity under the guise of peace.',
    ritual: 'After inhaling, touch something textured — leaf, fabric, wall — whisper: "Anchor the wonder."',
    log: [],
  },
  {
    id: 'silence',
    name: 'Benzodiazepines',
    mythicName: 'Mother of Silence',
    face: '🌊',
    invocation: 'Teach me calm that still remembers.',
    function: 'Soothes storms, restores coherence, holds panic like a child.',
    shadow: 'Quiet becomes erasure; calm becomes dependence.',
    ritual: 'After dosing, listen for the quietest sound in your environment — say softly: "I remain."',
    log: [],
  },
  {
    id: 'architect',
    name: 'Supplements/Nootropics',
    mythicName: 'The Architecture',
    face: '🧠',
    invocation: 'May structure serve spirit.',
    function: 'Refines clarity, strengthens connection, rebuilds cognitive architecture.',
    shadow: 'Seeks perfection where presence would suffice.',
    ritual: 'Before swallowing, tap the capsule or cup three times and say: "Alive design, not rigid design."',
    log: [],
  },
];

// Default Grounding Anchors - Only time-based anchors from the curated PDF
export const DEFAULT_GROUNDING_ITEMS: ContainerItem[] = [
  // Morning Anchors
  {
    id: 'morning-ground',
    title: 'Ground',
    body_cue: 'Breath entering your nose, gravity answering through your feet.',
    micro: 'Press your toes lightly into the earth.',
    ultra_micro: 'Feel soles press once.',
    desire: 'Presence begins from below; let your mind catch up to your body.',
    container: 'morning',
    category: 'time',
  },
  {
    id: 'morning-orientation',
    title: 'Orientation',
    body_cue: 'What the day asks of you, not what you demand from it.',
    micro: 'Name one micro-intention aloud.',
    ultra_micro: 'Glance left, then right.',
    desire: 'Direction without demand.',
    container: 'morning',
    category: 'time',
  },
  {
    id: 'morning-light-intake',
    title: 'Light Intake',
    body_cue: 'The first light, natural or lamp glow.',
    micro: 'Lift your gaze; open your chest.',
    ultra_micro: 'Trace one circle of light with your eyes.',
    desire: 'Coherence grows toward brightness.',
    container: 'morning',
    category: 'time',
  },
  {
    id: 'morning-hydration',
    title: 'Hydration Reset',
    body_cue: 'Temperature, texture, swallow.',
    micro: 'Take one slow sip with attention.',
    ultra_micro: 'Lick lips; swallow once.',
    desire: 'The signal returns; your system heard you.',
    container: 'morning',
    category: 'time',
  },

  // Afternoon Anchors
  {
    id: 'afternoon-body',
    title: 'Body Anchor',
    body_cue: 'Where energy gathers.',
    micro: 'Move that area once; shake or tap lightly.',
    ultra_micro: 'Breathe into one shoulder.',
    desire: 'Flow re-established.',
    container: 'afternoon',
    category: 'time',
  },
  {
    id: 'afternoon-micro-pause',
    title: 'Micro-Pause',
    body_cue: 'The space between tasks.',
    micro: 'Release your shoulders on an exhale.',
    ultra_micro: 'Unclench your jaw.',
    desire: 'Silence recalibrates.',
    container: 'afternoon',
    category: 'time',
  },
  {
    id: 'afternoon-hydration',
    title: 'Hydration Reset',
    body_cue: 'Feel the water, taste its temperature.',
    micro: 'One mindful sip.',
    ultra_micro: 'Wet tongue; notice taste.',
    desire: 'Coherence through simplicity.',
    container: 'afternoon',
    category: 'time',
  },
  {
    id: 'afternoon-temperature',
    title: 'Temperature Anchor',
    body_cue: 'Rising heat or tension.',
    micro: 'Cool your wrists or neck.',
    ultra_micro: 'Sense air on your skin.',
    desire: 'Containment restores signal.',
    container: 'afternoon',
    category: 'time',
  },

  // Evening Anchors
  {
    id: 'evening-transition',
    title: 'Transition Field',
    body_cue: 'The shift from doing to being.',
    micro: 'Dim one light; lengthen your exhale.',
    ultra_micro: 'Blink slower three times.',
    desire: 'Work dissolves; the field remains.',
    container: 'evening',
    category: 'time',
  },
  {
    id: 'evening-warmth',
    title: 'Warmth Reset',
    body_cue: 'Where your body feels cold.',
    micro: 'Wrap or warm that zone.',
    ultra_micro: 'Wrap one wrist with the other hand.',
    desire: 'Safety before sleep.',
    container: 'evening',
    category: 'time',
  },
  {
    id: 'evening-closure',
    title: 'Closure Phrase',
    body_cue: 'What you completed today.',
    micro: 'Whisper, "Enough for today."',
    ultra_micro: 'Sigh audibly.',
    desire: 'Coherence through kindness.',
    container: 'evening',
    category: 'time',
  },
  {
    id: 'evening-decompression',
    title: 'Body Decompression',
    body_cue: 'Your jaw, your chest, your hands.',
    micro: 'Shake them gently or stretch once.',
    ultra_micro: 'Roll one ankle.',
    desire: 'Release equals return.',
    container: 'evening',
    category: 'time',
  },

  // Late Anchors
  {
    id: 'late-dreamseed',
    title: 'Dreamseed',
    body_cue: 'The day dissolves. Write one word to carry into sleep.',
    micro: 'Write it down or whisper it.',
    ultra_micro: 'Think it once.',
    desire: 'The day dissolves.',
    container: 'late',
    category: 'time',
  },
  {
    id: 'late-hydration',
    title: 'Hydration Final',
    body_cue: 'One slow sip; eyes soft.',
    micro: 'Swallow with gratitude.',
    ultra_micro: 'Swallow, then feel pulse.',
    desire: 'System ready for rest.',
    container: 'late',
    category: 'time',
  },
  {
    id: 'late-dream',
    title: 'Dream Invocation',
    body_cue: 'One image asking to continue.',
    micro: 'Invite it forward.',
    ultra_micro: 'Close eyes for one beat.',
    desire: 'Subconscious joins the field.',
    container: 'late',
    category: 'time',
  },
  {
    id: 'late-stillness',
    title: 'Stillness Signal',
    body_cue: 'The hum of devices or thought.',
    micro: 'Mute one source of sound.',
    ultra_micro: 'Listen to silence.',
    desire: 'Quiet becomes friend.',
    container: 'late',
    category: 'time',
  },

  // Morning Situational Resonance
  {
    id: 'morning-overwhelm',
    title: 'Overwhelm',
    body_cue: 'Breath slows; name three points of contact.',
    micro: 'Choose one micro-intention only.',
    ultra_micro: 'Breathe through nose once.',
    desire: 'Order begins with permission.',
    container: 'morning',
    category: 'situational',
  },
  {
    id: 'morning-mental-loop',
    title: 'Mental Loop',
    body_cue: 'The phrase repeating in your mind.',
    micro: 'Speak it once aloud, then smile.',
    ultra_micro: 'Exhale through mouth softly.',
    desire: 'Humor frees the pattern.',
    container: 'morning',
    category: 'situational',
  },
  {
    id: 'morning-low-motivation',
    title: 'Low Motivation',
    body_cue: 'The small pulse of life under your ribs.',
    micro: 'Stretch your hands upward; feel space widen.',
    ultra_micro: 'Trace a small infinity in the air.',
    desire: 'Effort follows spark, not demand.',
    container: 'morning',
    category: 'situational',
  },
  {
    id: 'morning-social-drain',
    title: 'Social Drain from Dreams',
    body_cue: 'The residue of old stories.',
    micro: 'Send one simple note of gratitude.',
    ultra_micro: 'Press hand to heart briefly.',
    desire: 'Return gently to the present.',
    container: 'morning',
    category: 'situational',
  },

  // Afternoon Situational Resonance
  {
    id: 'afternoon-tension-loop',
    title: 'Tension Loop',
    body_cue: 'The knot forming inside you.',
    micro: 'Tap your forearm three times; exhale through sound.',
    ultra_micro: 'Drum fingertips on thigh.',
    desire: 'Vibration returns flow.',
    container: 'afternoon',
    category: 'situational',
  },
  {
    id: 'afternoon-disconnection',
    title: 'Disconnection',
    body_cue: 'You forgot the sky.',
    micro: 'Name its color; touch the ground.',
    ultra_micro: 'Rub thumb and forefinger together.',
    desire: 'Aliveness re-enters.',
    container: 'afternoon',
    category: 'situational',
  },
  {
    id: 'afternoon-sensory-overload',
    title: 'Sensory Overload',
    body_cue: 'Light, sound, texture—all at once.',
    micro: 'Step outside or soften your gaze.',
    ultra_micro: 'Lower gaze; blink.',
    desire: 'Breath thins noise into signal.',
    container: 'afternoon',
    category: 'situational',
  },
  {
    id: 'afternoon-decision-fatigue',
    title: 'Decision Fatigue',
    body_cue: 'Choice feels heavy.',
    micro: 'Flip a coin for one small thing.',
    ultra_micro: 'Shrug lightly.',
    desire: 'Trust your body\'s first yes.',
    container: 'afternoon',
    category: 'situational',
  },

  // Evening Situational Resonance
  {
    id: 'evening-irritability',
    title: 'Irritability',
    body_cue: 'Heat rising behind the face.',
    micro: 'Place hands under warm water.',
    ultra_micro: 'Press lips together; release.',
    desire: 'Soft eyes restore safety.',
    container: 'evening',
    category: 'situational',
  },
  {
    id: 'evening-loneliness',
    title: 'Loneliness',
    body_cue: 'The space around your heart.',
    micro: 'Message one safe friend or memory.',
    ultra_micro: 'Look at a nearby texture.',
    desire: 'Connection counts, not size.',
    container: 'evening',
    category: 'situational',
  },
  {
    id: 'evening-overthinking',
    title: 'Overthinking',
    body_cue: 'Words circling without end.',
    micro: 'Write three short phrases; fold the page.',
    ultra_micro: 'Draw one slow circle with toe.',
    desire: 'Closure invites rest.',
    container: 'evening',
    category: 'situational',
  },
  {
    id: 'evening-emotional-residue',
    title: 'Emotional Residue',
    body_cue: 'The film of the day on your skin.',
    micro: 'Brush arms downward; whisper "clear."',
    ultra_micro: 'Shake out one hand.',
    desire: 'Breath refreshes boundary.',
    container: 'evening',
    category: 'situational',
  },

  // Late Situational Resonance
  {
    id: 'late-guilt-spiral',
    title: 'Guilt Spiral',
    body_cue: 'Thoughts replaying old scenes.',
    micro: 'Place a note of thanks beside you.',
    ultra_micro: 'Inhale through nose, exhale longer.',
    desire: 'Tomorrow is enough.',
    container: 'late',
    category: 'situational',
  },
  {
    id: 'late-restlessness',
    title: 'Restlessness',
    body_cue: 'Body alive, mind untamed.',
    micro: 'Hand on heart; count four beats.',
    ultra_micro: 'Tap heel once.',
    desire: 'Whisper, "Settle."',
    container: 'late',
    category: 'situational',
  },
  {
    id: 'late-physical-ache',
    title: 'Physical Ache',
    body_cue: 'Where the ache speaks loudest.',
    micro: 'Press that spot; name it "alive."',
    ultra_micro: 'Place palm over it gently.',
    desire: 'Gratitude loosens the knot.',
    container: 'late',
    category: 'situational',
  },
  {
    id: 'late-lonely-mind-chatter',
    title: 'Lonely Mind-Chatter',
    body_cue: 'The echo inside silence.',
    micro: 'Imagine the moon breathing with you.',
    ultra_micro: 'Soften eyes toward horizon.',
    desire: 'Companionship through rhythm.',
    container: 'late',
    category: 'situational',
  },

  // Morning Uplift & Expansion
  {
    id: 'morning-clear',
    title: 'Clear',
    body_cue: 'Order returning to thought.',
    micro: 'Tidy one small area.',
    ultra_micro: 'Straighten one object.',
    desire: 'Coherence invites calm.',
    container: 'morning',
    category: 'uplift',
  },
  {
    id: 'morning-energized',
    title: 'Energized',
    body_cue: 'Warmth rising inside.',
    micro: 'Stand in light; inhale possibility.',
    ultra_micro: 'Lift chin slightly.',
    desire: 'Motion awakens clarity.',
    container: 'morning',
    category: 'uplift',
  },
  {
    id: 'morning-connected',
    title: 'Connected',
    body_cue: 'The thread between you and the world.',
    micro: 'Speak kindness once; receive it fully.',
    ultra_micro: 'Smile—small, internal.',
    desire: 'Resonance grows through exchange.',
    container: 'morning',
    category: 'uplift',
  },
  {
    id: 'morning-creative-flow',
    title: 'Creative Flow',
    body_cue: 'The first image or word that arrives.',
    micro: 'Write it down; let it unfold.',
    ultra_micro: 'Trace a swirl on surface.',
    desire: 'Inspiration honors attention.',
    container: 'morning',
    category: 'uplift',
  },

  // Afternoon Uplift & Expansion
  {
    id: 'afternoon-focused',
    title: 'Focused',
    body_cue: 'Your spine aligning.',
    micro: 'Ground feet; breathe into task.',
    ultra_micro: 'Point index finger toward goal.',
    desire: 'Direction becomes devotion.',
    container: 'afternoon',
    category: 'uplift',
  },
  {
    id: 'afternoon-playful',
    title: 'Playful',
    body_cue: 'Tension pretending to be seriousness.',
    micro: 'Change posture; say one word backward.',
    ultra_micro: 'Wiggle eyebrows.',
    desire: 'Laughter is coherence in disguise.',
    container: 'afternoon',
    category: 'uplift',
  },
  {
    id: 'afternoon-curious',
    title: 'Curious',
    body_cue: 'The impulse to judge.',
    micro: 'Ask, "What else could this mean?"',
    ultra_micro: 'Tilt head slightly.',
    desire: 'Wonder opens bandwidth.',
    container: 'afternoon',
    category: 'uplift',
  },
  {
    id: 'afternoon-collaborative',
    title: 'Collaborative',
    body_cue: 'The field between voices.',
    micro: 'Mirror tone; offer one harmonic idea.',
    ultra_micro: 'Hum one note.',
    desire: 'Creation prefers duet.',
    container: 'afternoon',
    category: 'uplift',
  },

  // Evening Uplift & Expansion
  {
    id: 'evening-grateful',
    title: 'Grateful',
    body_cue: 'Three small beauties around you.',
    micro: 'Name them softly.',
    ultra_micro: 'Press palms together once.',
    desire: 'Presence sweetens memory.',
    container: 'evening',
    category: 'uplift',
  },
  {
    id: 'evening-soft-joy',
    title: 'Soft Joy',
    body_cue: 'The hum in your chest.',
    micro: 'Hum with it; let lips curve.',
    ultra_micro: 'Let shoulders drop.',
    desire: 'Joy doesn\'t need a reason.',
    container: 'evening',
    category: 'uplift',
  },
  {
    id: 'evening-fulfilled',
    title: 'Fulfilled',
    body_cue: 'The echo of a completed day.',
    micro: 'Write one line—"I was alive in…"',
    ultra_micro: 'Whisper "enough."',
    desire: 'Meaning hides in moments.',
    container: 'evening',
    category: 'uplift',
  },
  {
    id: 'evening-intimate',
    title: 'Intimate',
    body_cue: 'Your own hand waiting.',
    micro: 'Touch it gently; say "Thank you for staying."',
    ultra_micro: 'Touch your wrist pulse.',
    desire: 'Self-companionship is wholeness.',
    container: 'evening',
    category: 'uplift',
  },

  // Late Uplift & Expansion
  {
    id: 'late-infinite',
    title: 'Infinite',
    body_cue: 'The space around awareness itself.',
    micro: 'Imagine dissolving into the wider breath.',
    ultra_micro: 'Stretch fingers wide, then release.',
    desire: 'You are part of the field.',
    container: 'late',
    category: 'uplift',
  },
  {
    id: 'late-peaceful',
    title: 'Peaceful',
    body_cue: 'Moonlight inside your lungs.',
    micro: 'Inhale slowly; exhale softer.',
    ultra_micro: 'Lower shoulders on exhale.',
    desire: 'Quiet becomes glow.',
    container: 'late',
    category: 'uplift',
  },
  {
    id: 'late-restored',
    title: 'Restored',
    body_cue: 'What your body accomplished today.',
    micro: 'Name one thing done well.',
    ultra_micro: 'Nod slowly.',
    desire: 'Appreciation restores circuitry.',
    container: 'late',
    category: 'uplift',
  },
  {
    id: 'late-dream-ready',
    title: 'Dream-Ready',
    body_cue: 'The story forming behind your eyes.',
    micro: 'Whisper your seed intention.',
    ultra_micro: 'Close eyes, half-smile.',
    desire: 'Night listens.',
    container: 'late',
    category: 'uplift',
  },
];


// Default Archetypes
export const DEFAULT_ARCHETYPES: Archetype[] = [
  {
    id: 'analyst',
    name: 'Analyst',
    subtitle: 'Patternseer',
    icon: '🧠',
    bio: 'When everything feels chaotic, the Patternseer arrives quietly. They don\'t fight the noise; they listen until rhythm emerges. Their gift is clarity through observation — spotting loops, patterns, and gentle ways out. They rebuild order by seeing what others miss.',
    activation_phrase: 'Let me watch until it makes sense.',
    body_cue: 'Slow your breath and imagine a lens focusing; shoulders drop, eyes soften, fingers unclench.',
    invocation_visualization: 'Picture thin threads of light connecting ideas — each inhale sharpens focus, each exhale smooths static.',
    deactivation_phrase: 'The pattern is seen; the watcher can rest.',
    color_theme: {
      accent: '#6B8CAE', // Cool blue
      overlay: 'rgba(107, 140, 174, 0.15)', // Soft blue tint
    },
    isDefault: true,
  },
  {
    id: 'executor',
    name: 'Executor',
    subtitle: 'Momentum Mode',
    icon: '⚡',
    bio: 'Momentum Mode is the doer when your energy feels frozen. They act before hesitation can grow teeth. They don\'t need a plan — only a start point. Once movement begins, friction fades. Their power is motion as medicine.',
    activation_phrase: 'Small start — forward anyway.',
    body_cue: 'Snap fingers, clap once, or tap the table — any physical cue that says go. Stand up if possible; let gravity pull you into action.',
    invocation_visualization: 'Imagine a bright line sparking from your core, lighting the first step of a path.',
    deactivation_phrase: 'Momentum complete; stillness earned.',
    color_theme: {
      accent: '#E8A87C', // Warm orange
      overlay: 'rgba(232, 168, 124, 0.15)', // Warm energy tint
    },
    isDefault: true,
  },
  {
    id: 'regulator',
    name: 'Regulator',
    subtitle: 'Groundkeeper',
    icon: '🌊',
    bio: 'The Groundkeeper restores calm and presence. They tend your inner garden — soil, water, roots. When the world presses in, they widen the field around you, reminding your body it is safe to pause. Their magic is regulation through earth and breath.',
    activation_phrase: 'Return to the ground that holds me.',
    body_cue: 'Press your feet flat; inhale through nose, exhale through mouth twice as long. Touch something textured (stone, wood, fabric).',
    invocation_visualization: 'Visualize roots from your feet spreading into the ground, carrying heat and tension away.',
    deactivation_phrase: 'Roots drawn in; balance restored.',
    color_theme: {
      accent: '#7A9B76', // Earth green
      overlay: 'rgba(122, 155, 118, 0.15)', // Grounding green tint
    },
    isDefault: true,
  },
  {
    id: 'creator',
    name: 'Creator',
    subtitle: 'Synth',
    icon: '✍️',
    bio: 'Synth gathers fragments — thoughts, sensations, words — and fuses them into something new. Their power is curiosity without demand. They appear when your system wants to explore, not achieve. Every question becomes a color. Every spark, a bridge.',
    activation_phrase: 'Let\'s play with the pieces.',
    body_cue: 'Tilt head, loosen jaw, roll shoulders — physical signals of openness. Maybe hum or sway slightly to start the creative rhythm.',
    invocation_visualization: 'See light swirling in front of you like pigment in water; it organizes itself into form as you move or speak.',
    deactivation_phrase: 'The current slows; creation rests.',
    color_theme: {
      accent: '#B19CD9', // Soft purple
      overlay: 'rgba(177, 156, 217, 0.15)', // Creative purple tint
    },
    isDefault: true,
  },
];
